version: 2

project_name: ssh-tgzx

dist: dist

git:
  ignore_tags:
    - "saved/*"

before:
  hooks:
    - go mod tidy
    - go tool gofumpt -l -w .
    - go generate ./...

builds:
  - id: "{{ .ProjectName }}"
    main: ./cmd/{{ .ProjectName }}
    binary: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    flags:
      - -trimpath

archives:
  - id: default
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "0.0.0-SNAPSHOT-{{.ShortCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
